# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_auto_20170716_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='app01.Tag'),
        ),
    ]
