# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_auto_20170716_0828'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article2tag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='article2tag',
            name='article',
        ),
        migrations.RemoveField(
            model_name='article2tag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Article2Tag',
        ),
    ]
