# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_auto_20170718_0835'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article2tag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='article2tag',
            name='article',
        ),
        migrations.RemoveField(
            model_name='article2tag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Article2Tag',
        ),
    ]
